# Generated by Django 6.0.1 on 2026-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author_username',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='accroche',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mot / Accroche'),
        ),
        migrations.AddField(
            model_name='post',
            name='auteur_signature',
            field=models.CharField(blank=True, max_length=255, verbose_name='Auteur / Signature'),
        ),
        migrations.AddField(
            model_name='post',
            name='citation',
            field=models.TextField(blank=True, verbose_name='Citation'),
        ),
        migrations.AddField(
            model_name='post',
            name='handle',
            field=models.CharField(blank=True, max_length=100, verbose_name='@handle'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Image'),
        ),
    ]
